### ISSUE TITLE
"理由/証拠" の引数でリンク追加を強制化する

### ISSUE THREAD

**Issue by m1sk9** [AzisabaNetwork/AzisabaReport#5]
https://github.com/AzisabaNetwork/AzisabaReport/blob/2e97b03ffd4b90d522ea360853d8d02d694e44f2/src/main/java/net/azisaba/azisabareport/commands/ReportCommand.java#L42-L46

https://github.com/AzisabaNetwork/AzisabaReport/blob/2e97b03ffd4b90d522ea360853d8d02d694e44f2/src/main/java/net/azisaba/azisabareport/commands/ReportCommand.java#L75-L77

引数 `理由/証拠` でリンクを追加することを強制化し、証拠を出させないとそもそものレポートを法務部に送れないようにする

**Comment by acrylic-style** [comment]
✅ in https://github.com/AzisabaNetwork/AzisabaReport/commit/68755ae660503dcfd2ce0fed74e7f083143163c4
